### ISSUE TITLE
[RAYSTORM PC] Music does stops playing after pausing

### ISSUE THREAD

**Issue by ViperAcidZX** [ayuanx/ogg-winmm#11]
I was trying out this wrapper with my copy of 2000/2001 CyberFront Windows port of RayStorm, and while it works, music plays and with the correct tracks after ripping them from my own installation disc, but if I pause during gameplay, the music does not resume where I paused the game like in other PC games that relies on the CD drive for music playback like Quake, it just stops playing until the game decides to play the next track with how it picks the music tracks.

**Comment by ayuanx** [comment]
Device ID 0x1 will collide with real WinMM devices when there are calls to open devices like MIDI. This is because Windows is not aware of the emulated CD Audio device, so Windows will always starts from ID 0x1 when devices like MIDI are opened.

If you real want that game to work, you can either hack the game to bypass device ID check, or hack the ogg-winmm.dll binary replacing device ID 0xCDDA with 0x0001.

**Comment by YELLO-belly** [comment]
Yes, if the game opens multiple MCI devices concurrently then the device ID's would conflict. Usually however if a game opens mci device for say video playback it closes it before opening the cdaudio device and vice versa so no conflict should occur. Similarly for midi playback, etc. Of course if the game is programmed in a way that multiple mci devices remain open then it would be an issue. (Hence a winmm.ini option for manual device id override only.)

I remember reading on the Vogons forums and in Dxwnd discussion about more games that prefer the first available device id. In the dxwnd cda proxy they went for a solution where a dummy wave file is created and opened just to check which MCI device ID's are available for use but that is probably a bit overkill.

I won't bother you with this issue more and I hope I have not derailed the topic too much from RayStorm...

**Comment by ayuanx** [comment]
Try the latest build which implements support for pause/resume.

**Comment by ViperAcidZX** [comment]
The newest update seemed to have fixed the issue for me with RayStorm PC from my testing so far, thank you!
