### ISSUE TITLE
Pitfall The Mayan Adventure no music play

### ISSUE THREAD

**Issue by Hexaae** [ayuanx/ogg-winmm#12]
Doesn't seem to work with Pitfall unfortunately.
/Music subdir contains the audio tracks (Track02.ogg... etc.) and winmm.dll + ini copied to game dir as per instructions.
Works fine using DAEMON Tools Lite and mounting my original CD image.

**Comment by ayuanx** [comment]
Use this debug build to generate and upload a log.
https://github.com/ayuanx/ogg-winmm/files/8777495/winmm_debug.zip

**Comment by Hexaae** [comment]
Mmmh, no log generated in the game dir (?)
I can send you the files for testing, please send me a mail to the address in this encrypted paste.sh https://paste.sh/bJWToyiV#LsebQl-n6XbHsl1dMYs2pN5z

**Comment by ayuanx** [comment]
If no log is generated, it means this game does not use winmm.dll to play CD music.
There are many ways to play CD-DA tracks not necessarily using winmm.dll.

**Comment by Hexaae** [comment]
There is a winmm.dll in the exe though:
![image](https://user-images.githubusercontent.com/8591462/221507073-c4a2ec2b-467a-48ab-b904-16b1ed71fdf6.png)

**Comment by ayuanx** [comment]
You have to run the game on WinXP or later.
Win98 and earlier versions do not support registered system DLL overloading from any arbitrary game folder.

**Comment by ayuanx** [comment]
There won't be any log generated if the DLL is not loaded.

**Comment by Hexaae** [comment]
Slick move... it worked renaming in the game exe "winmm.dll" to "wincd.dll" and renaming your winmm.dll. Here is the log, it seems to work but the game ignores Audio CD:

![image](https://user-images.githubusercontent.com/8591462/221540402-09e2c081-93a0-43b7-9335-6f8b83dd8f08.png)

Log:
```
ogg-winmm music directory is C:\Users\Luca\RetroGames\Pitfall\MUSIC
ogg-winmm searching tracks...
Track 02: 00:27 @ 0 seconds
Track 03: 00:44 @ 27 seconds
Track 04: 02:26 @ 71 seconds
Track 05: 03:43 @ 217 seconds
Track 06: 01:34 @ 440 seconds
Track 07: 04:07 @ 534 seconds
Track 08: 04:32 @ 781 seconds
Track 09: 02:32 @ 1053 seconds
Track 10: 01:38 @ 1205 seconds
Track 11: 03:53 @ 1303 seconds
Track 12: 03:00 @ 1536 seconds
Track 13: 03:14 @ 1716 seconds
Track 14: 03:52 @ 1910 seconds
Track 15: 04:10 @ 2142 seconds
Track 16: 04:18 @ 2392 seconds
Track 17: 03:01 @ 2650 seconds
Track 18: 01:43 @ 2831 seconds
Track 19: 02:14 @ 2934 seconds
Track 20: 01:55 @ 3068 seconds
Track 21: 01:53 @ 3183 seconds
Track 22: 00:26 @ 3296 seconds
Track 23: 02:16 @ 3322 seconds
Track 24: 00:43 @ 3458 seconds
Emulating total of 24 CD tracks.

```

**Comment by Hexaae** [comment]
Ok, it's the missing CD... If I run PITFALL.EXE in non-admin mode it will run fine except there is no CD music.
When I run the game in admin mode the game pops-up a requester saying the "Game must be run from CD" (???) when using wincd.dll... Using DAEMON Tools Lite CD image the game correctly finds and plays the CD music too (sound+music).

**Comment by ayuanx** [comment]
Never use "right click context menu" to directly run as admin, always use the checkbox in "right click-> properties -> compatibility" dialog.

For detailed explanation of why, see https://ayuanx.wordpress.com/2022/01/26/windows-run-as-administrator-working-directory-bug/

**Comment by Hexaae** [comment]
I use the MS-ACT shim _AdditiveRunAsHighest_ usually (same mechanic?), but thanks for the heads up about C:\Windows\System32\ path I didn't know.

**Comment by YELLO-belly** [comment]
I think Pitfall The Mayan Adventure is one of those games that check the length of the cdaudio tracks and if they do not precisely match then the music will not play. The ogg-winmm emulation will only get you the length of the ogg tracks in seconds (if I am not mistaken). It can not achieve the precision of TMSF (track, minutes, seconds, frames) that is possible with a real CD. Not to mention issues where a ripped music track might not match the original track length due to the ripping / conversion method used, etc...

Assuming you are running the game from the original CD _(not an image file that may also have inaccurate track lengths)_ you could have better luck with Dxwnd and its ability to fake the track lengths or to play the disc using IOCTL instead of the MCI API. As I do not have this game I was not able to test it so there are no guarantees but you could also try it with the updated [cdaudio-winmm](https://github.com/YELLO-belly/cdaudio-winmm) project to see if it can handle it.

**Comment by Hexaae** [comment]
@YELLO-belly
@ayuanx  
Thank you! With your help I was finally able to find a way to play Pitfall the Mayan Adventure and Earthworm Jim SE with audio track correctly pausing/stopping and... auto-restarting track when finished! 🏆

How to, mixing all the hints (including my shims):
- using cdaudio-winmm as suggested by YELLO-belly, renamed as wincd.dll and hex-edited the single occurrence inside the game exe of winmm.dll -> wincd.dll
- CD game image mounted with DAMON Tools Lite
- running the game with _AdditiveRunAsHighest_ MS-ACT shim to enable CD detection
 
My own shims (MS-ACT available from https://learn.microsoft.com/it-it/windows-hardware/get-started/adk-install#adkwin10, install just the first entry "Application Compatibility Tools" 8.2MB):
![image](https://user-images.githubusercontent.com/8591462/221718811-b5fd15bb-95dc-44e6-a5c8-6157b58d9675.png)

**Comment by Hexaae** [comment]
> I think Pitfall The Mayan Adventure is one of those games that check the length of the cdaudio tracks and if they do not precisely match then the music will not play. The ogg-winmm emulation will only get you the length of the ogg tracks in seconds (if I am not mistaken). It can not achieve the precision of TMSF (track, minutes, seconds, frames) that is possible with a real CD. Not to mention issues where a ripped music track might not match the original track length due to the ripping / conversion method used, etc...
> 
> Assuming you are running the game from the original CD _(A cd image file might also have inaccurate track lengths)_ you could have better luck with Dxwnd and its ability to fake the track lengths or to play the disc using IOCTL instead of the MCI API. As I do not have this game I was not able to test it so there are no guarantees but you could also try it with the updated [cdaudio-winmm](https://github.com/YELLO-belly/cdaudio-winmm) project to see if it can handle it.

May I ask you a feature to solve a problem with cdaudio-winmm (sorry but I see no "Issues" button on the GitHub project):
cdaudioplr.exe sometimes takes too long to launch indirectly (as the game will load and use the new dll).
Can you add a sort of user-defined delay (1-2 secs) after the dll gets loaded, to let it run cdaudioplr.exe before the game goes on searching for the inserted audio CD?

**Comment by YELLO-belly** [comment]
Sorry about that. "Issues" are now enabled for cdaudio-winmm fork. Please re-post your question there.
