### ISSUE TITLE
Feature request - multiple Music folders

### ISSUE THREAD

**Issue by StenApp** [ayuanx/ogg-winmm#13]
Hi,

i ran into a problem with Rainbow Six Rogue Spear.
The main game and it‘s two addons share the same folder where their exe files reside.
Is it possible that each exe uses another Music folder?

R6RS.exe
Addon1.exe
Addon2.exe
Music
Music1
Music2

**Comment by MIvanchev** [comment]
@ayuanx it's shared by a separate copy exists in the memory of every process and you can get the EXE name from https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlea so in theory it could be done if you have a mapping in the INI file.

**Comment by ayuanx** [comment]
Sorry I reckon that I don't have the intention to do that, since there is rarely any use case.
My philosophy is to always keep things as simple as possible.  

But you don't have to agree with my philosophy anyway, since it is open source you always have the option to fork it and implement that in your fork.

**Comment by MIvanchev** [comment]
I agree with your philosophy very much and am very grateful that you actively work on the fork that allows us to play our favorite games.

@StenApp there is a workaround you can use, create 3 copies of the file called: 1inmm.dll, 2inmm.dll, 3inmm.dll, rename the library references in the EXE files. Then in each Xinmm.dll you need to change the binary for the string MUSIC to MUSI1, MUSI2 and MUSI3 respectively and name the folders MUSI1, MUSI2, MUSI3. I can't find the reference for the binary string with hexcurse though but I'll try again later!

**Comment by StenApp** [comment]
It might be a rare case, but there are games out there.
Maybe we need a workaround for these.

**Comment by MIvanchev** [comment]
@StenApp that'll work I just need to figure out what to change with hexcurse, can't find the string "MUSIC" so I guess the strcat code has been inlined and the string is added char by char somewhere. Gimme a few.

**Comment by MIvanchev** [comment]
@StenApp Change the byte at 00000CD2 from `\MUS` to `\1US', `\2US`, `\3US` and then name your folders `1usic`, `2usic`, `3usic`.
