### ISSUE TITLE
Quake II Support?

### ISSUE THREAD

**Issue by OpenRift412** [ayuanx/ogg-winmm#15]
Just thought I'd leave a suggestion here. Vanilla Quake II, for whatever reason, never seems to work with any ogg-winmm forks, and I've only had success using _inmm.ini, which requires patching the EXE and having an external service running in the background, which also isn't very portable either. Could you perhaps look into seeing if it's possible to implement support for Quake II?

**Comment by MIvanchev** [comment]
Maybe the EXE is not the only file that loads the DLL?

**Comment by OpenRift412** [comment]
> Maybe the EXE is not the only file that loads the DLL?

I mean, I don't think so. Nothing seems to suggest that that's the case.

**Comment by ayuanx** [comment]
You can try this debug version and upload the log.
[winmm.zip](https://github.com/ayuanx/ogg-winmm/files/12385342/winmm.zip)

**Comment by OpenRift412** [comment]
> Also, describe exactly what you need to do below in details would help.
> 
> >
This guide shows you how _inmm.dll installation/patching works. It's pretty much the same for all games.
https://www.play-old-pc-games.com/compatibility-tools/_inmm-dll-tutorial/

**Comment by OpenRift412** [comment]
> You can try this debug version and upload the log. [winmm.zip](https://github.com/ayuanx/ogg-winmm/files/12385342/winmm.zip)

I put this in my directory using the unpatched quake2.exe and ran it. Didn't generate a log from what I see.

**Comment by ayuanx** [comment]
> I put this in my directory using the unpatched quake2.exe and ran it. Didn't generate a log from what I see.
That means the game is not using "winmm.dll" to play CD tracks.

If you can upload the game exe file somewhere, I may have a look.

**Comment by OpenRift412** [comment]
> > I put this in my directory using the unpatched quake2.exe and ran it. Didn't generate a log from what I see.
> 
> That means the game is not using "winmm.dll" to play CD tracks.
> 
> If you can upload the game exe file somewhere, I may have a look.

Here's a ZIP containing the EXE (this is version 3.20, the last official version of vanilla Quake II)
[quake2.zip](https://github.com/ayuanx/ogg-winmm/files/12386772/quake2.zip)

Opening up the EXE in a hex editor, there is one reference to winmm.dll at offset 00049526, but maybe it's using winmm.dll for something else? I dunno.

**Comment by ayuanx** [comment]
Wait, on which OS were you running the game?  Don't tell me you are running on Win95/98.

**Comment by ayuanx** [comment]
Anyway, I tested Quake 2 on Win8, and I don't find any issue.
The music plays just fine. No patch or anything special is required.

**Comment by OpenRift412** [comment]
> Wait, on which OS were you running the game? Don't tell me you were running on Win95/98.

I'm running on Windows 11 lol



> Anyway, I tested Quake 2 on Win8, and I didn't find any issue. The music plays just fine. No patch or anything special is required. You only need to "enable cd music" in the game options.

Windows 8? Try testing it on Win10 or 11, see if you get the same results there, since it's entirely possible that 10/11 have changes that cause this issue.

**Comment by ayuanx** [comment]
I don't think it is the problem of OS version, unless not a single game works on that specific OS.
It seems it is your own problem.
You need to figure out yourself why it works on other machines but not on your machine.

**Comment by OpenRift412** [comment]
> I don't think it is the problem of OS version, unless not a single game works on that specific OS. It seems it is your own problem. You need to figure out yourself why it works on other machines but not on your machine.

I think you underestimate the changes between Windows versions and how much legacy functionality they've dropped since Windows 8. I've tested this on both my desktop and laptop and get the exact same results. 

Do I need to get someone else to test this setup on their PC for you to believe me?

**Comment by MIvanchev** [comment]
AFAIK Quake 2 uses multiple DLLs next to the EXE and it's very possible that one of them imports winmm.dll as well, check them all out in the hex editor and change all references. Look in the game's directory for DLLs.

**Comment by ayuanx** [comment]
No, you don't need to do any patch at all.

You may not believe my test, that's fine. But other people had done the same test much earlier than me. So pretty sure it is the problem of your own system.

https://www.doomworld.com/forum/post/2531620
![Screenshot 2023-08-21 at 00-45-50 id Software is re-organizing the Galactic Doompublic into the first ever Galactic Doompire](https://github.com/ayuanx/ogg-winmm/assets/3690492/6ce2c903-cf86-4c6e-9008-5edcf5aa4270)
