### ISSUE TITLE
Half-Life WON not having any music playback

### ISSUE THREAD

**Issue by Neutral-Markiplier** [ayuanx/ogg-winmm#18]
Greetings, it seems that this wrapper with the retail version (1.1.1.0 btw, to also have music with Blue Shift which isn't 1.1.1.0 and doesn't have .mp3 playback) of Half-Life isn't working, I've ripped the music from the CD, converted them to .ogg using [oggdropXPd](https://www.rarewares.org/ogg-oggdropxpd.php), put them in a `music` folder in the base directory and also put the .dll in the base directory. Reading the other issues, I installed the game in `C:\Games\Half-Life` btw.

**Comment by Neutral-Markiplier** [comment]
> You can try the debug version and upload the log. [winmm.zip](https://github.com/user-attachments/files/16529993/winmm.zip)

It seems that Half-Life crashes everytime I try to start the game or open the console now, even after I restore the non-debug winmm.dll, I close this issue as I am deleting it since I wouldn't want to troubleshoot this "bullshit" as this is a sudden change from it running ok before. I blame VALVe for making it bloated, Quake has few .dlls in comparison to Half-Life.

**Comment by HaajPaaj** [comment]
If you hex edit the exe and replace winmm.dll with _inmm.dll, the music playback will work. This was tested on 1.0.1.6.
