### ISSUE TITLE
Custom playback folder

### ISSUE THREAD

**Issue by Patrxgt** [ayuanx/ogg-winmm#19]
In rare cases some games (like Pandemonium 2) use "MUSIC" file (without any extensions) to run the MIDI files. Windows unfortunately doesn't recognizes which one is a file and which one is a folder and throws out an error when trying to make a MUSIC folder in the game's directory. That could be fixed by adding a possibility to configure the name of a folder to something else than MUSIC through the .ini file or a detection of more names for the folder (eg. AUDIO, SOUND etc.).

**Comment by ayuanx** [comment]
Indeed this is an issue. Windows does not allow a file and a folder to have the same name.

Implemented in https://github.com/ayuanx/ogg-winmm/releases/tag/v2024.10.24
