### ISSUE TITLE
Not work music in games MageSlayer, Take no Prisoners

### ISSUE THREAD

**Issue by lighteon** [ayuanx/ogg-winmm#20]
In this game music works only in Windows 98SE. In Windows XP+ music not worked

**Comment by ayuanx** [comment]
You can try this debug version and upload the log.

https://github.com/ayuanx/ogg-winmm/files/12385342/winmm.zip

**Comment by lighteon** [comment]
And ddraw-pal have issue with this games, too. This games view D3D Modes with ddraw-pal, but not change, say error.

**Comment by ayuanx** [comment]
You can try this test build to see whether it fixes the issue.

[winmm.zip](https://github.com/user-attachments/files/17714298/winmm.zip)

**Comment by ayuanx** [comment]
> And ddraw-pal have issue with this games, too. This games view D3D Modes with ddraw-pal, but not change, say error in windows xp+. But aqrit wrapper work correctly.

pal-ddraw does not support D3D yet, so it is expected that any games that require D3D will not work with pal-ddraw.

**Comment by lighteon** [comment]
> You can try this test build to see whether it fixes the issue.
> 
> [winmm.zip](https://github.com/user-attachments/files/17714298/winmm.zip)

Now it's work fine, thx.

> > And ddraw-pal have issue with this games, too. This games view D3D Modes with ddraw-pal, but not change, say error in windows xp+. But aqrit wrapper work correctly.
> 
> pal-ddraw does not support D3D yet, so it is expected that any games that require D3D will not work with pal-ddraw.

This games use DDRAW. But in game view D3D Modes. And aqurit wrapper not have issue with pallete emulation. ddraw-pal work right with gog release Necrodome game. Necrodome use early version of Vampire engine. Vampire engine use in MageSlayer and Take no prisoners, too,

**Comment by ayuanx** [comment]
> > You can try this test build to see whether it fixes the issue.
> > [winmm.zip](https://github.com/user-attachments/files/17714298/winmm.zip)
> 
> Now it's work fine, thx.
> 
> > > And ddraw-pal have issue with this games, too. This games view D3D Modes with ddraw-pal, but not change, say error in windows xp+. But aqrit wrapper work correctly.
> > 
> > 
> > pal-ddraw does not support D3D yet, so it is expected that any games that require D3D will not work with pal-ddraw.
> 
> This games use DDRAW. But in game view D3D Modes. And aqurit wrapper not have issue with pallete emulation. ddraw-pal work right with gog release Necrodome game. Necrodome use early version of Vampire engine. Vampire engine use in MageSlayer and Take no prisoners, too,

The early versions of D3D (i.e. D3D7/D3D8) were implemented as an extension of DDRAW. Currently pal-ddraw does not support such D3D extension. Due to how D3D7/8 interacts with DDRAW, I don't have any plan to support them, because that requires a fundamental change in the mechanism of how to create and intercept the calls.

**Comment by lighteon** [comment]
> > > You can try this test build to see whether it fixes the issue.
> > > [winmm.zip](https://github.com/user-attachments/files/17714298/winmm.zip)
> > 
> > 
> > Now it's work fine, thx.
> > > > And ddraw-pal have issue with this games, too. This games view D3D Modes with ddraw-pal, but not change, say error in windows xp+. But aqrit wrapper work correctly.
> > > 
> > > 
> > > pal-ddraw does not support D3D yet, so it is expected that any games that require D3D will not work with pal-ddraw.
> > 
> > 
> > This games use DDRAW. But in game view D3D Modes. And aqurit wrapper not have issue with pallete emulation. ddraw-pal work right with gog release Necrodome game. Necrodome use early version of Vampire engine. Vampire engine use in MageSlayer and Take no prisoners, too,
> 
> The early versions of D3D (i.e. D3D7/D3D8) were implemented as an extension of DDRAW. Currently pal-ddraw does not support such D3D extension. Due to how D3D7/8 interacts with DDRAW, I don't have any plan to support them, because that requires a fundamental change in the mechanism of how to create and intercept the calls.

MageSlayer have maxium DirectX 3 version with update 1.1. I hear you. And still use aqrit wrapper for Windows XP+, but ddraw-pal works right in Windows 98SE in this games...

**Comment by Zerodarkage** [comment]
P.S. (1)
Most of the "CD music wrappers" has this problem!
The alternate solution:
1 = Use a HEX editor and change WINMM.DLL to XINMM.DLL (Make a backup first)
2 = Rename the Wrapper WINMM.DLL to XINMM.DLL

P.S. (2)
Most of the "CD music wrappers" has this problem!
They don't loop the music... xD
"YELLO-belly" version always loop and without any skipping any parts of the music (For example: Mortal Kombat 4 )

P.S. (3)
Sorry for not opening a real ticket! :(
