### ISSUE TITLE
Compatibility database : SingleProcAffinity

### ISSUE THREAD

**Issue by Choum28** [ayuanx/ogg-winmm#4]
Hello,

Are you able to use the wrapper when you set "SingleProcAffinity" as compatibility fix in a game ?
I made a test with Rogue Spear, when I set Singleprocaffinity,  I have no music.

Sincerely,

**Comment by ayuanx** [comment]
Music playback requires CPU cycles periodically to fill in the buffers (e.g. once per hundreds of milliseconds).
If there is not enough CPU free cycles left (i.e. CPU time is completely occupied by the main thread of the game), music playback thread as a low priority will starve and you will not hear any music.

**Comment by Choum28** [comment]
Thank you.
