### ISSUE TITLE
Sega Rally 2 and Sega GT both fail to resume (or even restart) music after pausing the game

### ISSUE THREAD

**Issue by instinctualjealousy** [ayuanx/ogg-winmm#5]
Music is missing until next fresh music call (post-race, restart race, so on).

**Comment by leipero** [comment]
Doesn't work with V-Rally 2 Expert Edition, music plays properly for one track only, exit and start another and it doesn't work anymore, also, changing songs in game menu doesn't work either, option is grayed out (still plays track 1).

**Comment by ayuanx** [comment]
Resume was never officially supported, as specified in Microsoft doc:

> The MCI_RESUME command causes a paused device to resume the paused operation. Digital-video, VCR, and waveform-audio devices recognize this command. **Although CD audio, MIDI sequencer, and videodisc devices also recognize this command, the MCICDA, MCISEQ, and MCIPIONR device drivers do not support it.**

Probably it was supported before Win 2000 but that is it.

**Comment by ayuanx** [comment]
I can do a quick update so that both pause and resume are ignored.
After all, without support of resume, pause is meaningless.
