### ISSUE TITLE
AoE2 Gold doesn't work, its expansion AoE2X1 works

### ISSUE THREAD

**Issue by StenApp** [ayuanx/ogg-winmm#7]
Hi,

i tried to get AoE2 working with music, well the expansion works, but not the basic game.
When I use dxwnd then both work.

Can you please have a look what the matter with AoE2 is?

**Comment by StenApp** [comment]
Can i do something to support here?

**Comment by ayuanx** [comment]
You can try the latest release first.

**Comment by StenApp** [comment]
Tried it with the following result, expansion works, not so with the basic game.
Copied AoE2\Music\Track02.ogg of AoE2 in AoE2\age2_x1\Music and the expansion played it.
I attach a screenshot of basic game and expansion.

![AoE2](https://user-images.githubusercontent.com/32524257/167263228-ba640de0-4a8a-452f-8610-638f41a4bef6.PNG)
![AoE2 expansion](https://user-images.githubusercontent.com/32524257/167263230-ba095043-05a1-4f52-be86-4a99d75c8b4d.PNG)

**Comment by StenApp** [comment]
I ripped the music track of AoE2 basic game from another image and now it's playing.
I don't know why it works now, the old file had lots of crackling in the last third of the music track.

**Comment by StenApp** [comment]
I opened the empires2.exe in Hexeditor and searched for winmm, renamed it to winmx and saved the file.
Used this ogg winmm and renamed winmm.dll it to winmx.dll, now it works
